# Generated by Django 5.0.4 on 2024-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_id',
            field=models.FloatField(null=True),
        ),
    ]
