# Generated by Django 5.0.4 on 2024-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_clothing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_id',
            field=models.IntegerField(null=True),
        ),
    ]
